# Generated by Django 5.2.13 on 2026-05-13 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DESPESA', 'Despesa')], max_length=32)),
                ('descricao', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'CLASSIFICACAO',
                'ordering': ['descricao', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CLIENTE-FORNECEDOR', 'Cliente-Fornecedor'), ('FATURADO', 'Faturado')], max_length=32)),
                ('razao_social', models.CharField(max_length=255)),
                ('documento', models.CharField(blank=True, db_index=True, max_length=32)),
                ('inscricao_estadual', models.CharField(blank=True, max_length=32)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=120)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'PESSOAS',
                'ordering': ['razao_social', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APAGAR', 'A Pagar')], default='APAGAR', max_length=16)),
                ('numero_nota_fiscal', models.CharField(blank=True, max_length=64)),
                ('serie', models.CharField(blank=True, max_length=32)),
                ('data_emissao', models.CharField(blank=True, max_length=32)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observacao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classificacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='invoices.classificacao')),
                ('invoice_extraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='invoices.invoiceextraction')),
                ('faturado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_faturado', to='invoices.pessoa')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_fornecedor', to='invoices.pessoa')),
            ],
            options={
                'db_table': 'MOVIMENTOCONTAS',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao', models.CharField(max_length=64, unique=True)),
                ('numero_parcela', models.PositiveIntegerField(default=1)),
                ('data_vencimento', models.CharField(blank=True, max_length=32)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('forma_pagamento', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='invoices.movimentocontas')),
            ],
            options={
                'db_table': 'PARCELACONTAS',
                'ordering': ['movimento_id', 'numero_parcela', 'id'],
            },
        ),
    ]
